package org.msandaa.model;

import java.util.Date;

public class DataPoint {

	public final Station station;
	public final Date time;

	public DataPoint(Station station, Date time) {
		this.station = station;
		this.time = time;
	}

	// Autogenerated
	@Override
	public String toString() {
		return "DataPoint [station=" + station + ", time=" + time + "]";
	}

	// Autogenerated
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((station == null) ? 0 : station.hashCode());
		result = prime * result + ((time == null) ? 0 : time.hashCode());
		return result;
	}

	// Autogenerated
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DataPoint other = (DataPoint) obj;
		if (station == null) {
			if (other.station != null)
				return false;
		} else if (!station.equals(other.station))
			return false;
		if (time == null) {
			if (other.time != null)
				return false;
		} else if (!time.equals(other.time))
			return false;
		return true;
	}

}
